version: "3"

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go-hackernews
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./pkg/models/mysql/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    #env_file:
    #  - .env

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql-data:
    driver: local
